/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedPortalLinksRouteImport } from './routes/_authenticated/portal-links'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSemestersRouteImport } from './routes/_authenticated/semesters'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as ApiPublicStudentAuthRouteImport } from './routes/api/public/student-auth'
import { Route as PortalTokenIndexRouteImport } from './routes/portal.$token.index'
import { Route as PortalTokenRegisterRouteImport } from './routes/portal.$token.register'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalLinksRoute =
  AuthenticatedPortalLinksRouteImport.update({
    id: '/portal-links',
    path: '/portal-links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSemestersRoute = AuthenticatedSemestersRouteImport.update({
  id: '/semesters',
  path: '/semesters',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedCoursesRoute,
  } as any)
const ApiPublicStudentAuthRoute = ApiPublicStudentAuthRouteImport.update({
  id: '/api/public/student-auth',
  path: '/api/public/student-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenIndexRoute = PortalTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTokenRoute,
} as any)
const PortalTokenRegisterRoute = PortalTokenRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PortalTokenRoute,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/manual': typeof ManualRoute
  '/privacy': typeof PrivacyRoute
  '/student': typeof StudentRoute
  '/terms': typeof TermsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/portal-links': typeof AuthenticatedPortalLinksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/semesters': typeof AuthenticatedSemestersRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/api/public/student-auth': typeof ApiPublicStudentAuthRoute
  '/portal/$token/register': typeof PortalTokenRegisterRoute
  '/portal/$token/': typeof PortalTokenIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/manual': typeof ManualRoute
  '/privacy': typeof PrivacyRoute
  '/student': typeof StudentRoute
  '/terms': typeof TermsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/portal-links': typeof AuthenticatedPortalLinksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/semesters': typeof AuthenticatedSemestersRoute
  '/sessions': typeof AuthenticatedSessionsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/api/public/student-auth': typeof ApiPublicStudentAuthRoute
  '/portal/$token/register': typeof PortalTokenRegisterRoute
  '/portal/$token': typeof PortalTokenIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/check-in': typeof CheckInRoute
  '/manual': typeof ManualRoute
  '/privacy': typeof PrivacyRoute
  '/student': typeof StudentRoute
  '/terms': typeof TermsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/portal-links': typeof AuthenticatedPortalLinksRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/semesters': typeof AuthenticatedSemestersRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/portal/$token': typeof PortalTokenRouteWithChildren
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/api/public/student-auth': typeof ApiPublicStudentAuthRoute
  '/portal/$token/register': typeof PortalTokenRegisterRoute
  '/portal/$token/': typeof PortalTokenIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/check-in'
    | '/manual'
    | '/privacy'
    | '/student'
    | '/terms'
    | '/announcements'
    | '/assignments'
    | '/billing'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/history'
    | '/portal-links'
    | '/reports'
    | '/scan'
    | '/semesters'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/portal/$token'
    | '/courses/$courseId'
    | '/api/public/student-auth'
    | '/portal/$token/register'
    | '/portal/$token/'
    | '/api/public/webhooks/paystack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/check-in'
    | '/manual'
    | '/privacy'
    | '/student'
    | '/terms'
    | '/announcements'
    | '/assignments'
    | '/billing'
    | '/courses'
    | '/dashboard'
    | '/departments'
    | '/history'
    | '/portal-links'
    | '/reports'
    | '/scan'
    | '/semesters'
    | '/sessions'
    | '/settings'
    | '/students'
    | '/courses/$courseId'
    | '/api/public/student-auth'
    | '/portal/$token/register'
    | '/portal/$token'
    | '/api/public/webhooks/paystack'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/check-in'
    | '/manual'
    | '/privacy'
    | '/student'
    | '/terms'
    | '/_authenticated/announcements'
    | '/_authenticated/assignments'
    | '/_authenticated/billing'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/history'
    | '/_authenticated/portal-links'
    | '/_authenticated/reports'
    | '/_authenticated/scan'
    | '/_authenticated/semesters'
    | '/_authenticated/sessions'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/portal/$token'
    | '/_authenticated/courses/$courseId'
    | '/api/public/student-auth'
    | '/portal/$token/register'
    | '/portal/$token/'
    | '/api/public/webhooks/paystack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckInRoute: typeof CheckInRoute
  ManualRoute: typeof ManualRoute
  PrivacyRoute: typeof PrivacyRoute
  StudentRoute: typeof StudentRoute
  TermsRoute: typeof TermsRoute
  PortalTokenRoute: typeof PortalTokenRouteWithChildren
  ApiPublicStudentAuthRoute: typeof ApiPublicStudentAuthRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-links': {
      id: '/_authenticated/portal-links'
      path: '/portal-links'
      fullPath: '/portal-links'
      preLoaderRoute: typeof AuthenticatedPortalLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/semesters': {
      id: '/_authenticated/semesters'
      path: '/semesters'
      fullPath: '/semesters'
      preLoaderRoute: typeof AuthenticatedSemestersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedCoursesRoute
    }
    '/api/public/student-auth': {
      id: '/api/public/student-auth'
      path: '/api/public/student-auth'
      fullPath: '/api/public/student-auth'
      preLoaderRoute: typeof ApiPublicStudentAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token/': {
      id: '/portal/$token/'
      path: '/'
      fullPath: '/portal/$token/'
      preLoaderRoute: typeof PortalTokenIndexRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/portal/$token/register': {
      id: '/portal/$token/register'
      path: '/register'
      fullPath: '/portal/$token/register'
      preLoaderRoute: typeof PortalTokenRegisterRouteImport
      parentRoute: typeof PortalTokenRoute
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCoursesRouteChildren {
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
}

const AuthenticatedCoursesRouteChildren: AuthenticatedCoursesRouteChildren = {
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
}

const AuthenticatedCoursesRouteWithChildren =
  AuthenticatedCoursesRoute._addFileChildren(AuthenticatedCoursesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPortalLinksRoute: typeof AuthenticatedPortalLinksRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSemestersRoute: typeof AuthenticatedSemestersRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPortalLinksRoute: AuthenticatedPortalLinksRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSemestersRoute: AuthenticatedSemestersRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalTokenRouteChildren {
  PortalTokenRegisterRoute: typeof PortalTokenRegisterRoute
  PortalTokenIndexRoute: typeof PortalTokenIndexRoute
}

const PortalTokenRouteChildren: PortalTokenRouteChildren = {
  PortalTokenRegisterRoute: PortalTokenRegisterRoute,
  PortalTokenIndexRoute: PortalTokenIndexRoute,
}

const PortalTokenRouteWithChildren = PortalTokenRoute._addFileChildren(
  PortalTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckInRoute: CheckInRoute,
  ManualRoute: ManualRoute,
  PrivacyRoute: PrivacyRoute,
  StudentRoute: StudentRoute,
  TermsRoute: TermsRoute,
  PortalTokenRoute: PortalTokenRouteWithChildren,
  ApiPublicStudentAuthRoute: ApiPublicStudentAuthRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
